### ISSUE TITLE
H2 DB throws uncatchable org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException

### ISSUE THREAD

**Issue by 662781** [662781/ProjectCodeGeneration#105]
Ik krijg de bovenstaande exception maar ik kan hem zelf niet opvangen in een catch blok.  Dit gebeurt tijdens het aanmaken van Users die al bestaande informatie bevatten, waar ook een constraint op staat via de User Entity (username, email en phone nr). 

Het is de bedoeling dat ik deze exception vang en afhandel in een try-catch en aan de frontend een HTTP Status Code en een bericht meegeef.

**Comment by wimmelstein** [comment]
Ik stel voor dat je eerst een cucumber test schrijft. Dat moet niet al te moeilijk zijn. Die gaat zeker falen, maar dan kun je wel met debug doorheen stappen om te kijken waar het fout gaat. En als het dan oplost, slaagt die test. Probeer die aanpak eens

**Comment by wimmelstein** [comment]
I have not received a comment in 5 days. I will close this issue now.
